 * Serving Flask app 'proxy'
 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.31.45.58:5000
[33mPress CTRL+C to quit[0m
210.183.100.33 - - [07/Mar/2025 03:18:41] "OPTIONS /generate HTTP/1.1" 200 -
[2025-03-07 03:20:56,166] ERROR in proxy: ìš”ì²­ ì „ë‹¬ ì˜¤ë¥˜: HTTPConnectionPool(host='54.180.123.29', port=8000): Max retries exceeded with url: /generate (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x71c47b96cb00>, 'Connection to 54.180.123.29 timed out. (connect timeout=None)'))
210.183.100.33 - - [07/Mar/2025 03:20:56] "[35m[1mPOST /generate HTTP/1.1[0m" 500 -
