 * Serving Flask app 'proxy'
 * Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.31.45.58:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:210.183.100.33 - - [07/Mar/2025 04:47:52] "OPTIONS /generate HTTP/1.1" 200 -
ERROR:proxy:Exception on /generate [POST]
Traceback (most recent call last):
  File "/home/ubuntu/proxy_env/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/proxy_env/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/proxy_env/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/proxy_env/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/proxy_env/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/git_repo/proxy.py", line 31, in generate
    sample = copy.deepcopy(sample_template)
             ^^^^
NameError: name 'copy' is not defined. Did you forget to import 'copy'
INFO:werkzeug:210.183.100.33 - - [07/Mar/2025 04:47:53] "[35m[1mPOST /generate HTTP/1.1[0m" 500 -
